<%
  const kinds = catalog.connectorKinds || [];
  const oscillator = (types || []).find((entry) => entry.name === 'Oscillator');
  const oscillatorModulatableParams = (oscillator?.fields || [])
    .filter((field) => field.modulatable)
    .map((field) => ({
      key: field.name,
      label: field.label || helpers.startCase(field.name),
      min: field.min,
      max: field.max,
      modulationKind: field.modulationKind || 'absolute',
      modulationOutMin:
        field.modulationOutMin !== undefined ? field.modulationOutMin : field.min,
      modulationOutMax:
        field.modulationOutMax !== undefined ? field.modulationOutMax : field.max,
    }));
  const shell = catalog.shell || {};
  const dump = (value) => JSON.stringify(value, null, 2);
%>
// Generated by Clay — do not edit by hand.
// Regenerate with: clay generate

export const connectorKinds = <%- dump(kinds) %> as const;

export const connectorKindsByKey = {
<% kinds.forEach((kind, index) => { %>
  '<%= kind.key %>': connectorKinds[<%= index %>],
<% }); %>
} as const;

export type ConnectorKindKey = keyof typeof connectorKindsByKey;

export const usgsConnector = connectorKindsByKey['usgs_earthquakes'];

export const oscillatorDefaults = <%- dump(catalog.oscillatorDefaults) %> as const;

export const modulatorDefaults = <%- dump(catalog.modulatorDefaults) %> as const;

export const oscillatorModulatableParams = <%- dump(oscillatorModulatableParams) %> as const;

export const shellCreateActions = <%- dump(shell.createActions || []) %> as const;

export const shellPaletteCategories = <%- dump(shell.paletteCategories || []) %> as const;

export const shellPatchTabs = <%- dump(shell.patchTabs || []) %> as const;

export const shellAuthActions = <%- dump(shell.authActions || []) %> as const;

export function getConnectorKind(kindKey: string) {
  if (kindKey in connectorKindsByKey) {
    return connectorKindsByKey[kindKey as ConnectorKindKey];
  }
  return undefined;
}

export function modulatableChannelsForKind(kindKey: string) {
  const kind = getConnectorKind(kindKey);
  if (!kind) return [];
  return kind.channels.filter((channel) => channel.modulatable);
}
