// Generated by Clay — do not edit by hand.
// Regenerate with: clay generate

import { initTRPC, TRPCError } from '@trpc/server';
import { z } from 'zod';

import type { TrpcContext } from '../trpc-context.js';
import {
  ForbiddenError,
  NotFoundError,
  VersionConflictError,
  patchCreate,
  patchDelete,
  patchGet,
  patchList,
  patchRename,
  patchReplaceGraph,
} from './handlers.js';

const t = initTRPC.context<TrpcContext>().create();

function mapError(error: unknown): never {
  if (error instanceof VersionConflictError) {
    throw new TRPCError({ code: 'CONFLICT', message: error.message });
  }
  if (error instanceof NotFoundError) {
    throw new TRPCError({ code: 'NOT_FOUND', message: error.message });
  }
  if (error instanceof ForbiddenError) {
    throw new TRPCError({ code: 'FORBIDDEN', message: error.message });
  }
  throw error;
}

const requireUser = t.middleware(({ ctx, next }) => {
  if (!ctx.user) {
    throw new TRPCError({ code: 'UNAUTHORIZED' });
  }
  return next({
    ctx: {
      ...ctx,
      user: ctx.user,
    },
  });
});

const authed = t.procedure.use(requireUser);

const graphNodeBase = z.object({
  id: z.string(),
  patchId: z.string(),
  label: z.string().optional(),
  positionX: z.number(),
  positionY: z.number(),
});

const connectorSchema = graphNodeBase.extend({
  kindKey: z.string(),
  feedUrl: z.string().optional(),
  pollIntervalMs: z.number().optional(),
  playbackHz: z.number().optional(),
});

const modulatorSchema = graphNodeBase.extend({
  channelKey: z.string(),
  targetParam: z.string(),
  inMin: z.number(),
  inMax: z.number(),
  outMin: z.number(),
  outMax: z.number(),
});

const oscillatorSchema = graphNodeBase.extend({
  waveform: z.string(),
  frequencyHz: z.number(),
  gain: z.number(),
});

<%
  const effectType = (types || []).find((entry) => entry.name === 'Effect');
  const graphBaseFieldNames = new Set(['id', 'patchId', 'label', 'positionX', 'positionY']);
  function zodForField(field) {
    let zod = 'z.unknown()';
    if (field.type === 'string') zod = 'z.string()';
    else if (field.type === 'number') zod = 'z.number()';
    else if (field.type === 'boolean') zod = 'z.boolean()';
    else if (field.type === 'timestamp') zod = 'z.string()';
    else if (field.type === 'json' || field.type === 'array') zod = 'z.unknown()';
    if (!field.required) zod += '.optional()';
    return zod;
  }
  const effectExtraFields = ((effectType && effectType.fields) || []).filter(
    (field) => !graphBaseFieldNames.has(field.name),
  );
%>
const effectSchema = graphNodeBase.extend({
<% effectExtraFields.forEach((field) => { %>
  <%= field.name %>: <%= zodForField(field) %>,
<% }); %>
});

const wireSchema = z.object({
  id: z.string(),
  patchId: z.string(),
  sourceNodeId: z.string(),
  targetNodeId: z.string(),
  sourceHandle: z.string().optional(),
  targetHandle: z.string().optional(),
});

export const appRouter = t.router({
  user: t.router({
    me: authed.query(({ ctx }) => ctx.user),
  }),
  patch: t.router({
    list: authed.query(async ({ ctx }) => {
      try {
        return await patchList(ctx.user.id);
      } catch (error) {
        mapError(error);
      }
    }),
    get: authed
      .input(z.object({ id: z.string() }))
      .query(async ({ ctx, input }) => {
        try {
          return await patchGet(ctx.user.id, input);
        } catch (error) {
          mapError(error);
        }
      }),
    create: authed
      .input(z.object({ name: z.string().min(1) }))
      .mutation(async ({ ctx, input }) => {
        try {
          return await patchCreate(ctx.user.id, input);
        } catch (error) {
          mapError(error);
        }
      }),
    rename: authed
      .input(
        z.object({
          id: z.string(),
          name: z.string().min(1),
          expectedVersion: z.number().int().positive(),
        }),
      )
      .mutation(async ({ ctx, input }) => {
        try {
          return await patchRename(ctx.user.id, input);
        } catch (error) {
          mapError(error);
        }
      }),
    delete: authed
      .input(
        z.object({
          id: z.string(),
          expectedVersion: z.number().int().positive(),
        }),
      )
      .mutation(async ({ ctx, input }) => {
        try {
          return await patchDelete(ctx.user.id, input);
        } catch (error) {
          mapError(error);
        }
      }),
    replaceGraph: authed
      .input(
        z.object({
          id: z.string(),
          expectedVersion: z.number().int().positive(),
          connectors: z.array(connectorSchema),
          modulators: z.array(modulatorSchema),
          oscillators: z.array(oscillatorSchema),
          effects: z.array(effectSchema),
          wires: z.array(wireSchema),
        }),
      )
      .mutation(async ({ ctx, input }) => {
        try {
          return await patchReplaceGraph(ctx.user.id, input);
        } catch (error) {
          mapError(error);
        }
      }),
  }),
});

export type AppRouter = typeof appRouter;
