<%
  const modelTypes = (types || []).filter((type) => type.persist !== false && type.name !== 'ConnectorKind');
  function snake(name) {
    return name.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
  }
  function pgColumn(field) {
    const col = snake(field.name);
    const name = field.name;
    if (field.type === 'number' && name === 'version') return "integer('" + col + "').notNull().default(1)";
    if (field.type === 'number') return "doublePrecision('" + col + "')" + (field.required ? '.notNull()' : '');
    if (field.type === 'boolean') return "boolean('" + col + "')" + (field.required ? '.notNull()' : '');
    if (field.type === 'timestamp') return "timestamp('" + col + "', { withTimezone: true })" + (field.required ? '.notNull()' : '');
    if (field.type === 'json' || field.type === 'array') return "jsonb('" + col + "')" + (field.required ? '.notNull()' : '');
    const base = "text('" + col + "')" + (field.required ? '.notNull()' : '');
    if (name === 'id') return base + '.primaryKey()';
    return base;
  }
  function tableName(typeName) {
    const map = {
      User: 'users',
      Patch: 'patches',
      Connector: 'connectors',
      Modulator: 'modulators',
      Oscillator: 'oscillators',
      Effect: 'effects',
      Wire: 'wires',
    };
    return map[typeName] || typeName.toLowerCase() + 's';
  }
  function exportName(typeName) {
    const map = {
      User: 'users',
      Patch: 'patches',
      Connector: 'connectors',
      Modulator: 'modulators',
      Oscillator: 'oscillators',
      Effect: 'effects',
      Wire: 'wires',
    };
    return map[typeName] || typeName.charAt(0).toLowerCase() + typeName.slice(1) + 's';
  }
  const fieldTypes = new Set();
  modelTypes.forEach((type) => {
    (type.fields || []).forEach((field) => {
      if (field.type === 'number' && field.name === 'version') fieldTypes.add('integer');
      else if (field.type === 'number') fieldTypes.add('doublePrecision');
      else if (field.type === 'boolean') fieldTypes.add('boolean');
      else if (field.type === 'timestamp') fieldTypes.add('timestamp');
      else if (field.type === 'json' || field.type === 'array') fieldTypes.add('jsonb');
      else fieldTypes.add('text');
    });
  });
  const drizzleImports = ['pgTable', ...Array.from(fieldTypes)].sort();
%>
// Generated by Clay — do not edit by hand.
// Regenerate with: clay generate

import {
<% drizzleImports.forEach((name) => { %>
  <%- name %>,
<% }); %>
} from 'drizzle-orm/pg-core';

<% modelTypes.forEach((type) => {
  const table = tableName(type.name);
  const exp = exportName(type.name);
%>
export const <%- exp %> = pgTable('<%- table %>', {
<% (type.fields || []).forEach((field) => { %>
  <%= field.name %>: <%- pgColumn(field) %>,
<% }); %>
});

<% }); %>

export const schema = {
<% modelTypes.forEach((type) => {
  const exp = exportName(type.name);
%>
  <%- exp %>,
<% }); %>
};
