<%
  function tsType(field) {
    const t = field.type;
    if (t === 'string') return 'string';
    if (t === 'number') return 'number';
    if (t === 'boolean') return 'boolean';
    if (t === 'timestamp') return 'string';
    if (t === 'json') return 'unknown';
    if (t === 'array') return 'unknown[]';
    return 'unknown';
  }
  const modelTypes = types || [];
%>
// Generated by Clay — do not edit by hand.
// Regenerate with: clay generate

<% modelTypes.forEach((type) => { %>
export type <%= type.name %> = {
<% (type.fields || []).forEach((field) => {
  const optional = field.required ? '' : '?';
%>
  <%= field.name %><%= optional %>: <%= tsType(field) %>;
<% }); %>
};

<% }); %>

export type PatchGraphPayload = {
  connectors: Connector[];
  modulators: Modulator[];
  oscillators: Oscillator[];
  wires: Wire[];
};

export type PatchWithGraph = Patch & PatchGraphPayload;
